### ISSUE TITLE
Socket Hang upについて質問させてください

### ISSUE THREAD

**Issue by OnigiriJoe** [senyoltw/homebridge-irkit#2]
homebridge-irkitを使用して、信号送信のリクエストをiPhoneのHome Appから要求すると
1度目は期待した動作をするのですが、2回目以降はFailしてしまいます。

homebridgeのlogは以下のような感じになります。

```
[登録名] Setting power state to on
[登録名] IRKit power function succeeded!
[登録名] Setting power state to on
[登録名] socket hang up
[登録名] IRKit power function failed!
```

このsocket hang upの原因がわからずに、困っております。
なお、わたしの環境は以下のようになっています。

```
Mac OS Sierra 10.12.3
node -v v6.9.4
npm -v 3.10.10
```

なにかお分かりになることはないでしょうか？
よろしくお願いします。

**Comment by senyoltw** [comment]
すみません。自分も初めてみるエラーなので解決の手助けになるかどうかわからないのですが、
socket hang upというエラーならば、次のような理由でエラーになってると思います。

homebridge-irkitはnode.js標準のhttpモジュールを使用しています。
なので、エラーとしては

_http_client.jsにある
https://github.com/nodejs/node/blob/9a5d47542d2e9e2874188251dc670d14929fe6f3/lib/_http_client.js
```
function createHangUpError() {
  var error = new Error('socket hang up');
  error.code = 'ECONNRESET';
  return error;
}
```
部分だと思います(多分)。なので
ECONNRESET	54	※Connection reset by peer	接続は相手からリセットされた
http://www.wdic.org/w/TECH/errno
になるかと思います。

同じ赤外線信号を公式サイトにあるとおりにcurlコマンドで送った場合は同じように2回目以降は失敗するでしょうか。
http://getirkit.com/

もしcurl2連続で失敗するならirkit側に問題があるかもしれません。

curl2連続が成功したらhomebridge-irkitもしくはhomebridge-irkitからirkitに至る何かで問題がありそうです。

もしcurlコマンドが連続で成功したなら、それをシェルスクリプトにして、
https://github.com/senyoltw/homebridge-cmd
でコマンドを登録すれば(根本的な問題はともかく)連続使用でも問題はなくなるかとおもいます。

**Comment by OnigiriJoe** [comment]
返信ありがとございます。

以下を試して見ました。

1回目
```
% curl -I "http://192.168.1.20/messages" -H "X-Requested-With: curl" -d '{"format":"raw","freq":38,"data":[データの中身]}'
HTTP/1.0 200 OK
Access-Control-Allow-Origin: *
Server: IRKit/3.0.0.0.g85190b1
Content-Type: text/plain
```
2回目
```
% curl -I "http://192.168.1.20/messages" -H "X-Requested-With: curl" -d '{"format":"raw","freq":38,"data":[データの中身]}'
curl: (52) Empty reply from server
```
3回目
```
% curl -I "http://192.168.1.20/messages" -H "X-Requested-With: curl" -d '{"format":"raw","freq":38,"data":[データの中身]}'

curl: (56) Recv failure: Connection reset by peer
```

という結果になりました。
2回目のEmptyというのは、もしかしたら2回目のリクエストが早かったせいかもしれません。
3回目はコマンドの応答がなくなり、しばらくするとConnection reset by peerとなりました。

homebridgeを利用している友人はこういう問題は起こっていないようですが、
IRKit自体が友人のものは生産中止になる以前のもの、わたしのは生産が再開されたあとのものという違いはあります。

**Comment by senyoltw** [comment]
curlでも失敗するということは、OSXからIRKitの通信経路の何処かでおかしなことになっていると思いますのでhomebridgeは関係無いです。
また、IRKitのファームウェアも特に生産再開前後で更新されてないので違いはないかと(中の基盤はわかりませんが)
https://github.com/irkit/device

OSXとIRKitで一度繋がったセッションが正常に破棄されてない可能性がありますが、判断はできません。

別のパソコンがあったら、そちらからcurlコマンドを2回叩いてみて、エラーがでるか試してみてはどうでしょうか。
もし正常であればOSXに何か問題がある。もし同様に別パソコンでもエラーが出たらIRKitに問題があると思います。その場合は交換対応を考えてはどうでしょうか。
homebridge-irkitには切り分けで問題ないことがわかったのでこのissueはクローズします。
